# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oV6g2Ejd3nqezKYMubxOXph9xpYT5jcM
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("img.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm2=cv2.imread("img2.jpg")
cv2_imshow(rasm2)

oqqora=cv2.cvtColor(rasm2, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm3=cv2.imread("img3.jpg")
cv2_imshow(rasm3)

oqqora=cv2.cvtColor(rasm3, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm4=cv2.imread("img4.jpg")
cv2_imshow(rasm4)

oqqora=cv2.cvtColor(rasm4, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm5=cv2.imread("img5.jpg")
cv2_imshow(rasm5)

"""# Новый раздел"""

oqqora=cv2.cvtColor(rasm5, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)